spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: postgres
    password: <<DB_PASSWORD>>
    driverClassName: org.postgresql.Driver
  jackson:
    default-property-inclusion: non_null
  flyway:
    baselineOnMigrate: true


  liquibase:
    change-log: /db/changelog/db.changelog-root.xml
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ticker-service-api:
  url:
    localhost:3000/api/v1

liquibase:
  secureParsing: false

app:
  jwt:
    secret: <<JWT_SECRET>>

server:
  port: 8080

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger
  api-docs:
    path: /api-docs