spring:
  datasource:
    url: jdbc:postgresql://192.168.1.100:5432/myportfolio-db
    username: postgres
    password: <<DB_PASSWORD>>
    driverClassName: org.postgresql.Driver
  jackson:
    default-property-inclusion: non_null
  flyway:
    baselineOnMigrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.100:8080/realms/myportfolio
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: myportfolio-client
      principal-attribute: preferred_username

  liquibase:
    change-log: /db/changelog/db.changelog-master.xml
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ticker-service-api:
  url:
    http://192.168.1.100:5000/api/v1

liquibase:
  secureParsing: false

app:
  jwt:
    secret: <<JWT_SECRET>>

server:
  port: 8000

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger
  api-docs:
    path: /api-docs